[build]
  command = "npm run build"
  publish = "build"   # agar CRA use kar rahe ho
  # publish = "dist"  # agar Vite use kar rahe ho

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
